### ISSUE TITLE
VerifyReport should be able to only "include" certain lines

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris-labs/interlok-verify-report#16]
Since verify report works off the standard output; it needs to be able to filter the output so that it only looks at lines it's interested in.

Since https://github.com/adaptris-labs/interlok-build-parent/blob/develop/verifyLog4j2.xml doesn't do anything with the pattern (i.e. it's just `%m%n`) then this means that verifyReport needs to make sense of the output from https://github.com/adaptris/interlok/pull/453

So, we should
* change verifyLog4j.xml so that it is `VERIFY_REPORT: %m%n` 
* Add a commandline switch to verifyReport so that it's `--include-only-lines-starting="VERIFY_REPORT"`
    * and obviously make the change to the underlying reporting code.

Which should mean that we can ignore all output from `-configcheck`

**Comment by mcwarman** [comment]
It looks like the current version works as is, with that PR.

More by luck than judgement:

```text
Task :interlokVerify
Bootstrap of Interlok 3.10-SNAPSHOT(2020-06-09:INTERLOK-2594_Config_Test) complete
file:/Users/warmanm/code/src/github.com/adaptris-labs/interlok-build-parent/verifyLog4j2.xml

Configuration loading test:
Passed.

Classpath duplication check.:
Warnings found;
Possible duplicates found.  Re-run with '-Dinterlok.bootstrap.debug=true' for more details.

Shared connection check.:
Passed.

Config check only; terminating
Interlok Verify contains warnings [1]
[Adapter(interlok-gcp-test)] has a MessageErrorHandler with no behaviour; messages may be discarded upon exception
```

I think its because we use the following in `interlokVerify`:
```gradle
def interlokVerify = tasks.register("interlokVerify", JavaExec) {
  //...
  standardOutput = new ByteArrayOutputStream()
  doLast {
    def verifyOutput = standardOutput.toString()
    //...
  }
}
```

As oppose to something like:

```gradle
def interlokVerify = tasks.register("interlokVerify", JavaExec) {
  doFirst {
    def output = new ByteArrayOutputStream()
  }
  //...
  standardOutput = output
  errorOutput = output
  doLast {
    def verifyOutput = output.toString()
    //...
  }
}
```
Ref: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html

It's probably still a worth while enhancement, but https://github.com/adaptris/interlok/pull/453 doesn't look to have effected it.
